### ISSUE TITLE
Import Clipboard Error

### ISSUE THREAD

**Issue by cjthomas730** [samapriya/Planet-GEE-Pipeline-CLI#1]
Hi, I was wanted to use your scripts for getting the planet imagery I have up in to EE. I'm running OS X and ran through the set-up / install process. However when I run python ppipe.py I get the following error message: 
``` python
Traceback (most recent call last):
  File "ppipe.py", line 13, in <module>
    import clipboard
ImportError: No module named clipboard
````

My apologies if this is a beginner question, but I can't seem to find documentation for clipboard, and I'm not quite sure what is causing this issue?

**Comment by samapriya** [comment]
clipboard module is not installed just install

pip install clipboard
to check if you meet all requirements you can run 
pip install -r requirements.txt
