### ISSUE TITLE
metadata file produced from files downloaded with the clip option of the old planet API aren't correct to use

### ISSUE THREAD

**Issue by jimoreira** [samapriya/Planet-GEE-Pipeline-CLI#12]

**Comment by jimoreira** [comment]
files produced with that tool end in **file_clip** and their metadata in **file_metadata_clip**. 
When the metadata tool produces the .csv file, cuts the name until metadata. So, the clip part isn't in the list of "id_no" of the produced file. 
That makes that the image name and metadata name, won't match. So, the message 
`No metadata exists for image 2123812_2017-12-15_RE2_3A_Analytic_clip : it will not be ingested` appears when `ppipe selupload`

**Comment by samapriya** [comment]
Hi @jimoreira 
This tool is not designed to handle Clipped data from Planet since it added the _Clip to filename while the metadata.xml does not have for this addon. There might be a way to change that in the future version easily so am going to add this as an enhancement request for now and hope to update it in the future

**Comment by jimoreira** [comment]
I'm trying to upload all that files anyway, but when:
1- change (by hand) the .csv "id_no" adding the "_clip", when selupload, i get the error
`invalid syntax (<unknown>, line 2)`

2- changing the images names, cutting the "_clip"  and producing the "metadata file" again, when selupload, I get the error, 
`invalid syntax (<unknown>, line 2)`

it's referred to the line 2 of "metadata_ingest_py"?? 
thanks for your help! I have a bunch of images downloaded in this way and I need to use them.

**Comment by samapriya** [comment]
The uploader and metadata parsing tools have been updated in version 0.4.4.
