### ISSUE TITLE
Error: Invalid value for "--geom": invalid GeoJSON

### ISSUE THREAD

**Issue by katherinehess** [samapriya/Planet-GEE-Pipeline-CLI#15]
Hi,

I am trying to use the dasync command and keep getting the error: Invalid value for "--geom": invalid GeoJSON. 

I cannot figure out what is going wrong- I even tried using geojsons that I have previously had success with using your porder CLI, but get the same error. I have attached the geojsons and this is the command I am running: 
ppipe dasync  --infile "calval.geojson" --item PSScene4Band --asset analytic  --local  "\fulldata" --start 2015-01-01 --end 2019-09-30 --cmin 0 --cmax .5

[Planet.zip](https://github.com/samapriya/Planet-GEE-Pipeline-CLI/files/3672463/Planet.zip)

Is there something wrong with the geojsons that I'm missing?
Thanks for your help!

**Comment by katherinehess** [comment]
Update: I've found that if I capitalize the JSON in .geoJSON, I no longer get any error messages, but the code still does not appear to do anything- nothing is downloaded. Does something else look wrong with my input parameters?

**Comment by katherinehess** [comment]
Found that my geojson had an extra ,0 at the end of each set of coordinates- closing this issue!

**Comment by samapriya** [comment]
Thanks for checking @katherinehess yeah the Planet API cannot handle z coordinates but glad it was an easy fix
