### ISSUE TITLE
Problem with ppipe space

### ISSUE THREAD

**Issue by guy1ziv2** [samapriya/Planet-GEE-Pipeline-CLI#5]
When running
!ppipe space --aoi "/content/map (1)_aoi.json" --asset "PSScene4Band analytic" --local "/content/planet"
I get an error
sh: 1: Syntax error: "(" unexpected

while if I use
!ppipe space --aoi "'/content/map (1)_aoi.json'" --asset "PSScene4Band analytic" --local "/content/planet"
it works fine. Other ppipe commands e.g. ppipe activatepl did not have that problem - in fact using "'/content/map (1)_aoi.json'" files for these while "/content/map (1)_aoi.json" works

**Comment by samapriya** [comment]
I think the issue is with the way in which the terminal versus command prompt resolves a " versus a ' . I will look into the issue and integrate some changes to handle this

**Comment by guy1ziv2** [comment]
To work it needed Both not either " or '
I think it has to do with the way you construct somewhere a sh command
