### ISSUE TITLE
Ppipe error for multiple geometries

### ISSUE THREAD

**Issue by guy1ziv2** [samapriya/Planet-GEE-Pipeline-CLI#6]
The tool breaks and returns 
Error code 400: {"field": {}, "general": [{"message": "unknown issue with search geometry"}]}
if the geojson has more than one feature. A clearer error message would be helpful, if not possible to have two or more polygons in the AOI filter

**Comment by samapriya** [comment]
It is not possible to have two or more Polygons and I will make the error message more clear on the next release
