### ISSUE TITLE
confusing command line parameters

### ISSUE THREAD

**Issue by guy1ziv2** [samapriya/Planet-GEE-Pipeline-CLI#7]
It is a bit confusing that sometimes you need to use --asst and sometimes --asset ; also --local is replaced with --pathway
Having the same names would be helpful (perhaps keeping old names working for compatibility)

**Comment by samapriya** [comment]
Thank you for the suggestions will integrate a common usage of terms in the next release. I think these are precursors from the standalone tools I have compiled into the overall CLI and I am making a note to get these changed in the next release.
