### ISSUE TITLE
ppipe space missing arguments

### ISSUE THREAD

**Issue by guy1ziv2** [samapriya/Planet-GEE-Pipeline-CLI#8]
I am running
!ppipe space --aoi "/content/map_aoi.json" --asset "PSScene4Band analytic_sr" --local "/content/planet"

which should work based on 
!ppipe space -h

but I get:
usage: download.py [-h] [--idlist IDLIST] [--query QUERY] [--search]
                   [--bbox XMIN YMIN XMAX YMAX] [--activate] [--check]
                   [--size SIZE] [--download DOWNLOAD] [--overwrite]
                   [--start-date START_DATE] [--end-date END_DATE]
                   [--satlist SATLIST] [--sats [SATS [SATS ...]]] [--key KEY]
                   [--debug]
                   item asset
download.py: error: too few arguments

**Comment by samapriya** [comment]
Fixed this in version 0.3.5, but not tested in Colab :)
