### ISSUE TITLE
Problem using version 0.38

### ISSUE THREAD

**Issue by RodrigoAgronomia** [samapriya/Planet-GEE-Pipeline-CLI#9]
Hello Samapriya, congratulations on your work!

I tried to install the last version using pip, everything works during installation, but when I try to run ppipe - h, I get the following error. I am using Windows 10, Anaconda3, Python 3.6:

  File "C:\Anaconda3\envs\GIS\Scripts\ppipe-script.py", line 11, in <module>
    load_entry_point('ppipe==0.3.8', 'console_scripts', 'ppipe')()
  File "C:\Anaconda3\envs\GIS\lib\site-packages\pkg_resources\__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Anaconda3\envs\GIS\lib\site-packages\pkg_resources\__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "C:\Anaconda3\envs\GIS\lib\site-packages\pkg_resources\__init__.py", line 2321, in load
    return self.resolve()
  File "C:\Anaconda3\envs\GIS\lib\site-packages\pkg_resources\__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Anaconda3\envs\GIS\lib\site-packages\ppipe\ppipe.py", line 7, in <module>
    from batch_copy import copy
ModuleNotFoundError: No module named 'batch_copy'

**Comment by samapriya** [comment]
Hi Rodrigo,
I have had issues myself when the system pip changes so I would recommend trying a **```pip install ppipe```** instead. Unfortunately I could not recreate the issue at my end for now.

**Comment by emarcari** [comment]
Hi Samapriya.
For users that try to call geeadd from a python 2.7 environment in Anaconda, a problem of missing 'batch_copy' module occurs. I guess the error comes from its package.

Do you know from which package the module comes into?
I guess the error should be fixed when installing it.

**Comment by samapriya** [comment]
Hi @emarcari 
First of all, **geeadd** is a different CLI [you can find it here](https://github.com/samapriya/gee_asset_manager_addon). As far as [geeadd](https://pypi.org/project/geeadd/) it is now using a dependency called _poster_ to handle large uploads, as such this is currently limited to only Python 2.7. I am working on getting an upgrade to make this work in Python 3 as well. batch_copy is already a part of the files included in the package. I just released version 0.2.8 but my recommendation is to use python 2 and hence 

```pip2 install geeadd --upgrade```
